import time
import contextlib
from typing import Dict, Any, List
from fastapi import FastAPI, Request, Response, status
from fastapi.responses import JSONResponse
from fastapi.exceptions import RequestValidationError
from starlette.exceptions import HTTPException as StarletteHTTPException

from app.config import settings
from app.routers import health, auth, predict
from app.middleware.cors import setup_cors
from app.middleware.logging import AuditLoggingMiddleware
from app.services.logging_service import app_logger, error_logger, log_security
from app.utils.limiter import limiter
from slowapi.errors import RateLimitExceeded
from slowapi.middleware import SlowAPIMiddleware

# Lifecycle context manager (lifespan)
@contextlib.asynccontextmanager
async def lifespan(app: FastAPI):
    app_logger.info("Initializing Secure & Compliant ML Security Pipeline Backend...")
    app_logger.info(f"Environment: {settings.ENVIRONMENT}")
    app_logger.info("Rate limiting active: max 100 req/60s")
    yield
    app_logger.info("Shutting down Secure & Compliant ML Security Pipeline Backend...")

# Initialize FastAPI application with lifespan context manager
app = FastAPI(
    title="Secure & Compliant ML Security Pipeline",
    description="Enterprise-grade secure machine learning inference backend.",
    version="1.0.0",
    docs_url="/docs" if settings.ENVIRONMENT != "production" else None,
    redoc_url="/redoc" if settings.ENVIRONMENT != "production" else None,
    lifespan=lifespan
)

# 1. Apply CORS Middleware
setup_cors(app)

# 2. Production-Ready Rate Limiter Setup (slowapi & Redis backend)
app.state.limiter = limiter
app.add_middleware(SlowAPIMiddleware)

@app.exception_handler(RateLimitExceeded)
async def custom_rate_limit_handler(request: Request, exc: RateLimitExceeded) -> JSONResponse:
    request_id = getattr(request.state, "request_id", "unknown")
    client_ip = request.client.host if request.client else "unknown"
    log_security(
        event="Rate limit exceeded",
        user="anonymous",
        ip_address=client_ip,
        status="BLOCKED"
    )
    return JSONResponse(
        status_code=status.HTTP_429_TOO_MANY_REQUESTS,
        content={
            "error": "Too Many Requests",
            "message": "Rate limit exceeded. Please try again later.",
            "request_id": request_id
        }
    )

# 3. Security Headers Middleware
@app.middleware("http")
async def add_security_headers(request: Request, call_next) -> Response:
    response = await call_next(request)
    # Prevent clickjacking attacks
    response.headers["X-Frame-Options"] = "DENY"
    # Disable MIME sniffing
    response.headers["X-Content-Type-Options"] = "nosniff"
    # Enable browser XSS protection
    response.headers["X-XSS-Protection"] = "1; mode=block"
    # Strict Transport Security (HSTS) - enforce HTTPS in production
    if settings.ENVIRONMENT == "production":
        response.headers["Strict-Transport-Security"] = "max-age=63072000; includeSubDomains; preload"
    # Content Security Policy (CSP)
    response.headers["Content-Security-Policy"] = "default-src 'self'; frame-ancestors 'none'; object-src 'none';"
    # Referrer Policy
    response.headers["Referrer-Policy"] = "no-referrer"
    return response

# 4. Apply Audit Logging Middleware
app.add_middleware(AuditLoggingMiddleware)

# 5. Custom Exception Handlers (Prevent stack trace & internal info leakage)
@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError) -> JSONResponse:
    """
    Handle Pydantic schema validation errors.
    Returns standardized format and hides raw internal error structures.
    """
    request_id = getattr(request.state, "request_id", "unknown")
    app_logger.warning(f"Request validation failed [{request_id}]: {exc.errors()}")
    
    return JSONResponse(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        content={
            "error": "Validation Error",
            "message": "The request payload failed validation rules.",
            "request_id": request_id,
            "details": [{"field": ".".join(map(str, err["loc"][1:])), "message": err["msg"]} for err in exc.errors()]
        }
    )

@app.exception_handler(StarletteHTTPException)
async def http_exception_handler(request: Request, exc: StarletteHTTPException) -> JSONResponse:
    """
    Standardize HTTP exceptions generated by FastAPI/Starlette.
    """
    request_id = getattr(request.state, "request_id", "unknown")
    return JSONResponse(
        status_code=exc.status_code,
        content={
            "error": "HTTP Error",
            "message": exc.detail,
            "request_id": request_id
        }
    )

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    """
    Catch-all exception handler to intercept unhandled server errors.
    Logs the stack trace internally, but returns a generic HTTP 500 response.
    """
    request_id = getattr(request.state, "request_id", "unknown")
    # Log details with stack trace to error log
    error_logger.exception(f"Unhandled exception occurred [{request_id}]: {exc}", extra={"request_id": request_id})
    
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={
            "error": "Internal Server Error",
            "message": "An unexpected error occurred. Please contact system support.",
            "request_id": request_id
        }
    )

# 6. Include API Routers
app.include_router(health.router)
app.include_router(auth.router)
app.include_router(predict.router)

# Lifespan events are managed via context lifespan manager in FastAPI initialization.
