name: Trigger auto deployment for fraud-front

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fraud-front-AutoDeployTrigger-86f27296-d12a-4f3b-a5f3-d2d4f32bef6c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FRAUDFRONT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FRAUDFRONT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FRAUDFRONT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: frauddetection-g9dgckffhkgegxg4.azurecr.io
          registryUsername: ${{ secrets.FRAUDFRONT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FRAUDFRONT_REGISTRY_PASSWORD }}
          containerAppName: fraud-front
          resourceGroup: Mohab
          imageToBuild: frauddetection-g9dgckffhkgegxg4.azurecr.io/fraud-front:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


